### PR TITLE
Fix language issues in README.md

### PR DESCRIPTION
**Pull request by mitchcurtis**

### CODE REVIEW

**Comment by denis-shienkov** [comment]
Could you please fix this conflicts and repeat again? :)

**Comment by denis-shienkov** [comment]
@mitchcurtis, ping. Have you planns to rebase this?

**Comment by mitchcurtis** [comment]
No, sorry, my contribution was more of an as-is thing. :D I wasn't expecting to have to rebase.

**Comment by denis-shienkov** [comment]
Then I'll close this MR.

**Pull request closed without merging**
